version: '3.8'

services:
  app:
    build: .
    container_name: liveprofile
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - SESSION_STRING=${SESSION_STRING}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
