services:
  app:
    build:
      context: .
      args:
        - API_ID=${API_ID}
        - API_HASH=${API_HASH}
        - SESSION_STRING=${SESSION_STRING}
    container_name: liveprofile
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    env_file:
      - .env
    
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 300M
        reservations:
          memory: 200M

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
